---
swap_size: 1G
users:
  - username: eshnnsessyn
    shell: /bin/bash
    create_home: 1
    add_groups: sudo
    comment: admin
    add_ssh_pub: 1
    path_to_pub: id_rsa.pub
    is_sudoer: 1
  - username: user
    shell: /bin/bash
    create_home: 1
    add_groups:
    comment: default user
    add_ssh_pub: 0
    path_to_pub:
    is_sudoer: 0
