---
- name: clone git repo to role directory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: ensure roles directory exists
      file:
        path: 'roles'
        state: directory
    - name: clone the git repo into the directory
      git:
        repo: 'git@github.com:Eshnnsessyn/lf-ansible-roles.git'
        dest: 'roles'
        version: main
        force: yes
