---
- name: Collect selected facts
  hosts: all
  gather_facts: false
  become: true

  tasks:
  - name: Collect nw and hw facts
    ansible.builtin.setup:
      gather_subset:
        - '!all'
        - '!min'
        - network
        - hardware

- name: Configure stage web servers
  hosts: web
  gather_facts: true
  roles:
    - role: common

